<?php

?>

<h2>Getting Started on AlumniHUB</h2>

<div style='padding:20px;'>
<span class='info'>Find the basic infomation you need to get started on the AlumniHUB</span>



<h6>Adding your AIESEC Information</h6>  
<p>First Thing you should do is add your AIESEC Information to the AlumniHUB.</p>
<p>Once you sign into the AlumniHUB find the "Add your AIESEC Information" button by the right side of the page.</p>
<br/><br/>
<img src='../../images/shot1.png' />
<br/><br/>
<p>Click on this and you would be taken to the page where you can add your basic AIESEC Infomation.</p>
<br/>
<img src='../../images/shot2.png' />
<br/><br/>
<p>You must fill the Basic AIESEC Information section. The Past role section is optional and can
be filled much later.</p>

</div>