<div id="left_content">

<h2>Alumni Directory</h2>
<span id='intro'>
Find the directory of all AIESEC Alumni Offices all across the Countries AIESEC is present in. Use this tool to locate the office, get necessary contact and connect with the Alumni Assosication in your country
</span>

<style type="text/css">
ul#offices li
{
	border:1px solid #a3a3a3;
	margin:3px;
	width:100px;
	height:100px;
	float:left;
	border-top:10px solid #f3f3f3;
}
</style>

<h3>National Offices</h3>

<ul id="offices">
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>

</ul>


</div>