<style>
div#staticcontent
{
	padding:20px;
}
</style>
<div id='staticcontent'>
<h2>About AlumniHub</h2>
<p>AlumniHub is a global networking site built by AIESEC International and AIESEC Alumni International. This is the official platform for 1 million AIESEC Alumni to reconnect, share, and create a positive impact after their active AIESEC career.
To get started, the most important steps for you to take are the followings:</p>
<p>
<ol>
<li>Add AIESEC Information: to make sure fellow Alumnus and AIESEC friends can find you not only based on your LinkedIn profile, but additional AIESEC Information. <a href='<?php echo Zend_Registry::get('url') ?>/settings'>Add AIESEC Information</a></li>
<li>Join the official global alumni group on LinkedIn: Go to <a href='http://www.linkedin.com/groups?gid=693' target='_blank'>AIESEC Alumni Global</a> on Linkedin in</li>
</ol>
</p>


<p>If you have any questions on how to take the most out of the platform, please write  to alumni@ai.aiesec.org!</p>


</div>