<style type='text/css'>
div#error_div
{
	padding-left:30px;
	padding-top:30px;
	
}


span.error_msg
{
	background-color:#FAF4F3;
	margin:10px;
	padding:10px;
	margin-left:0px;
	width:500px;
	display:block;
}

div#error_div li
{
	margin-bottom:5px;
	display:block;
}
</style>


<div id='error_div'>

<h4>Error!</h4>

<span class='error_msg'>
Errors were encountered while trying to update your profile. Please find below the error messages.

</span>
<ul>
<?php
foreach($this->errormsg as $k=>$v)
{
 echo "<li>- $v</li>";
 
}
?>
</ul>

<a href='/settings' class='btn primary'>Go Back</a>
</div>


