<!DOCTYPE html> 
<html lang="en"> 
    <head>
        
        <link rel="stylesheet" href="/styles/bootstrap.min.css">
        
        <link rel="stylesheet" href="/styles/master.css">
        <link rel="stylesheet" href="/styles/home.css">
        <title>Home</title>
    </head>
    
    
    
    <body>
        <div class="nav"></div>
        <div style="clear:both"></div>
          <div class="container">
          <div class="content">
           <div id="left">
          <?php 
          echo $this->layout()->content;
          ?>
          </div>
          <div id="profile_sidebar">
		    
          </div>
          
          
          </div>

            
            <div class="footer">
            <div><a>About AIESEC Alumni Hub</a>    <a>About AIESEC</a>    <a>Getting In Touch</a></div>
            </div>
            
          </div>
        
        
    </body>
    
</html>