<div id="left_content_profile">

<div id='my-modal' style='display:none'>
<br/>
<p style='text-align: center'><img src="<?php echo Zend_Registry::get('url')?>/images/roller2.gif" /></p>
<h5 style='text-align: center'>Saving...</h5>
<br/>

</div>





<h2>Your Profile</h2>
<div id="linkedin">
<h6>Your Profile on Linkedin</h6>
<div style="float:left;width:100px;">
<?php 
@session_start();
$profilepix =  $_SESSION['profilepix'];
$publiclink = $_SESSION['publiclink'];
echo "<img src='$profilepix' />";
?>
</div>

<div style="float:left;width:250px;">
<p><strong>First Name: </strong><?php echo $_SESSION['firstname'];?></p>
<p><strong>Last Name: </strong><?php echo $_SESSION['lastname'];?></p>
<p><strong>Industry: </strong><?php echo $_SESSION['industry'];?></p>
<p style='width:230px'><strong>Description: <br/></strong><?php echo $_SESSION['headline'];?></p>
<br/>
<p><a href='<?php echo "$publiclink" ?>' target='_blank' class="">Edit Your Linkedin Profile</a></p>
</div>


<div style="float:left;margin-top:-30px;width:480px;height:200px;background-color:#f9f9f9;padding:10px">
<h6>Your Connections on Linkedin</h6>
<?php 
/*@session_start();
if (!isset($_SESSION['connections']))
{
	
	$_SESSION['connections'] = $this->connections;
	echo $_SESSION['connections'];

}
else
{
	
	echo $_SESSION['connections'];
}*/
echo $this->connections;
?>

</div>




</div>

<hr/>
<div style="clear:both"></div>
<div id="tabs">
<ul class="tabs">
  <li class="active"><a href="#personal">Personal</a></li>
  <li><a href="#pastroles">Past Roles</a></li>
  <li><a href="#pastinternships">Past Internships</a></li>
  <li><a href="#pastevents">Past Events</a></li>
  <li><a href="#activities">Current Activities</a></li>
</ul>
 
<div class="pill-content">

  <div class="active" id="personal">
  <?php 
  //$this->profile
  $this->showprofile('personal','yes');
  ?>
  
  </div>
  
  <div id="pastroles">
  <?php 
  $this->showprofile('pastroles','yes');
  ?>
  </div>
  
  <div id="pastinternships">
  <?php 
  $this->showprofile('pastinternships','yes');
  ?>
  </div>
  
  <div id="pastevents">
  <?php 
  $this->showprofile('pastevents','yes');
  ?>
  
  </div>
  
  <div id="activities">
  <?php 
  $this->showprofile('activities','yes');
  ?>
  </div>
  
</div>
 
<script>
  $(function () {
    $('.tabs').tabs()
  })
</script>
</div>
</div>

<script type="text/javascript">
$(document).ready(function()
		{
	$("ul.alternate li:odd").css({'backgroundColor':'#f9f9f9'});
		}
	
		);
</script>




<script type="text/javascript" src="../../scripts/editprofile.js">
<!--

//-->
</script>

<script type='text/javascript' src='../../scripts/bootstrap-modal.js'>

</script>


