<style>
div#staticcontent
{
	padding:20px;
}
</style>
<div id='staticcontent'>
<h2>Contact Us</h2>
<p>AlumniHub is a global networking site built by AIESEC International and AIESEC Alumni International.</p>
<p>If you have any inquiry please do not hesitate to any of the following Emails</p> 

<h3>General Inquiries</h3>
<p>Luca Keresztesi</p>
<p>Vice President, AIESEC International</p>
<p>lucak@ai.aiesec.org</p>

<h3>Technical Inquiries</h3>
<p>Dade Aderemi</p>
<p>IM Manager, AIESEC International</p>
<p>dadepoa@ai.aiesec.org</p>





</div>