<?php 
$url = Zend_Registry::get('url');

?>
<!-- Add the things needed for the slider -->
<style type='text/css'>
.nivoSlider {
    position:relative;
    width:680px; /* Change this to your images width */
    height:236px; /* Change this to your images height */
    background:url(images/roller2.gif) no-repeat 50% 50%;

}
.nivoSlider img {
    position:absolute;
    top:0px;
    left:0px;
    display:none;
}
.nivoSlider a {
    border:0;
    display:block;
}
</style>
<link rel="stylesheet" href="./nivo/nivo-slider.css" type="text/css" media="screen" />
<script src="./nivo/jquery.nivo.slider.pack.js" type="text/javascript"></script>



<div id='welcomenote'>
<div id="slider" class="nivoSlider">

<a href='<?php echo Zend_Registry::get("url")?>/static/gettingstarted'><img src="images/slide3.png" alt="" /></a>
 	<a href='<?php echo Zend_Registry::get("url")?>/static/index/welcomeaddress'><img src="images/slide1.png" alt="" /></a>
    <a href='<?php echo Zend_Registry::get("url")?>/a2a/newsletter'><img src="images/slide2.png" alt="" /></a>
 
</div>

</div>

<!--<h6>Welcome to Alumni Hub</h6>
<p>AAI is the platform for AIESEC Alumni to achieve their potential on an international level</p>
<p>AIESEC Alumni International (AAI) is a registered international, non-political, independent and non for profit association, linking its memberships above and beyond culture, race, sex, citizenship, religion, economic system and branch, hierarchy and generation, based on non-mercantile relationships and a capital of trust. Through its memberships, the association will continue to promote international and cross-cultural understanding, in line with the founding principles of AIESEC, for the professional and personal development of its members and the good of society.</p>
<p><a href='<?php echo Zend_Registry::get("url")?>/static/index/welcomeaddress' class='btn'>Continue Reading</a></p>-->
<div id="left_content">

<h3>Recent Notifications on AlumniHub <img style="margin-left:5px;vertical-align:middle" src="<?php echo $url; ?>/images/notification.png" /></h3>

<div style="border:5px solid #f3f3f3; background-color:#fff;min-height:100px;margin:10px 23px">
<h3 class='small'>Notifications<!--  <img style="margin-left:5px;vertical-align:middle" src="<?php echo $url; ?>/images/notification.png" />--></h3>
<div id='notification'>
<?php 
$ev = $this->recentevents;

while(list($eid,$edesc,$time,$link,$linkdesc,$uname,$linkedin) = mysql_fetch_row($ev))
{
	echo "<p><strong>$uname</strong> just $edesc | <a href='$link'>$linkdesc</a></p>";
}
?>
</div>
</div>


<h3>Recent Activity on <img style="vertical-align:middle" src="<?php echo $this->baseUrl('images/recentlinkedin.png');?>" /></h3>


<?php 
//this is a controller variable
echo $this->recentlinkedin;
?>

<h3>Recent Posts From Alumni Of the World Unite <img style="vertical-align:middle;width:15px;height:15px" src="<?php echo $this->baseUrl('images/alumniworld.jpg');?>" /></h3>


<div class='frontrow'>
<?php 
//this is a view helper
echo $this->blogfeed('titles',5);

?>
</div>

<?php
echo $this->featuredisplay("Home");
?>

</div>
<script type="text/javascript">
$(window).load(function() {
    $('#slider').nivoSlider({controlNav: false,effect:'slideInRight',directionNav: false,pauseTime: 5000});
});
</script>