<div id='welcomenote'>
<h6>Welcome to Alumni Hub</h6>

<p>AAI is the platform for AIESEC Alumni to achieve their potential on an international level</p>
<p>AIESEC Alumni International (AAI) is a registered international, non-political, independent and non for profit association, linking its memberships above and beyond culture, race, sex, citizenship, religion, economic system and branch, hierarchy and generation, based on non-mercantile relationships and a capital of trust. Through its memberships, the association will continue to promote international and cross-cultural understanding, in line with the founding principles of AIESEC, for the professional and personal development of its members and the good of society.</p>
<p><a href='<?php echo Zend_Registry::get("url")?>/static/index/welcomeaddress' class='btn'>Continue Reading</a></p>
</div>
<div id="left_content">

<h3>Recent Activity on <img style="vertical-align:middle" src="<?php echo $this->baseUrl('images/recentlinkedin.png');?>" /></h3>


<?php 
//this is a controller variable
echo $this->recentlinkedin;
?>

<h3>Recent Posts From Alumni Of the World Unite <img style="vertical-align:middle;width:15px;height:15px" src="<?php echo $this->baseUrl('images/alumniworld.jpg');?>" /></h3>


<div class='frontrow'>
<?php 
//this is a view helper
echo $this->blogfeed('titles',5);

?>
</div>
<?php 
$url = Zend_Registry::get('url');

?>
<h3>Recent Notifications on AlumniHub <img style="margin-left:5px;vertical-align:middle" src="<?php echo $url; ?>/images/notification.png" /></h3>

<div style="border:5px solid #f3f3f3; background-color:#fff;min-height:100px;margin:10px 23px">




<h3 class='small'>Notifications<!--  <img style="margin-left:5px;vertical-align:middle" src="<?php echo $url; ?>/images/notification.png" />--></h3>








<div id='notification'>
<?php 
$ev = $this->recentevents;
if ($ev != null)
{
while(list($eid,$edesc,$time,$link,$linkdesc,$uname,$linkedin) = mysql_fetch_row($ev))
{
	echo "<p><strong>$uname</strong> just $edesc | <a href='$link'>$linkdesc</a></p>";
}
}
?>
</div>

</div>


<?php
echo $this->featuredisplay("Home");
?>

</div>
