<div id="left_content">
<span id='intro'>
AIESEC proudly recognizes some outstanding individuals that are making a positive change in their societies and are AIESEC alumni
</span>

<div id='inner_content'>
<p>The Global AIESEC Awards were launched in 2000 at the AIESEC International Congress in Edinburgh, Scotland. From having only the category of "Global Alumni Hall of Fame", the Global AIESEC Awards now also include the AIESEC Entrepreneurship and Leadership, the AIESEC Contribution Award and the Global Young Alumni Contribution Award. Winners of the three latter awards are eligible for another nomination for the Global Alumni Hall of Fame Award in later years if their profiles continue to grow.</p> 
 
<p>This re-structuring took place in order to ensure a proper representation and selection of awardees in every category. Practice of recent years showed different people should be nominated for each of the awards, and evaluation criteria differ. This does not affect any award winners retrospectively.</p> 
 
<p>Alumni can be nominated by AIESEC countries, individual alumni, Alumni groups/associations, and AIESEC International once a year during the nomination period in the spring of each year. The selection for the awards is done by a committee consisting of an alumnus of AIESEC International, a member of an AI Supervisory Group, President of AIESEC International and the Global Alumni Relations Manager.</p> 
 
<p>Through the Global AIESEC Awards we aim to:</p> 

<h5>Showcasing the impact of AIESEC</h5>
<p>The quality of our alumni and their contribution to and impact on society demonstrate and ensure the relevance of AIESEC and our activities.</p>

<h5>Profiling role models for AIESEC members</h5>
<p>Reinforce the leadership characteristics and attitudes desired in AIESEC by highlighting  role-modeling  alumni  who  exemplify  our  values  and  who  had  an outstanding contribution in AIESEC and within their community. Recognize Alumni, who put leadership for a positive impact on society and being a change agent into practice.</p>

<h5>Demonstrate the power of the AIESEC network</h5>
<p>The recipients of the Hall of Fame awards are examples of the caliber of people that form part of the AIESEC network. by positioning AIESEC alumni internally, it inspires the active membership to connect with AIESEC history and learn from past experiences.</p>

<h5>Recognize the achievements and contribution of our alumni</h5>
<p>Their contribution directly and indirectly allows for the creation of more and better AIESEC experiences and as AIESEC we want to celebrate their achievements with them.</p>


</div>


</div>
