<script type='text/javascript'>
$(document).ready(function()
		{
	$('a#linkedinlogin').click(function()
	{
		
	$('#my-modal').modal({
		  backdrop: false
		}).modal('show');
		}
		);
		}
		);
</script>


<div id='my-modal' style='display:none;'>
<br/>
<p style='text-align: center'><img src="<?php echo Zend_Registry::get('url')?>/images/roller2.gif" /></p>
<h5 style='text-align: center'>Contacting Linkedin...Login in...</h5>
<br/>

</div>



<?php 
			
?>            
                <div id="bleft">
                    <img src="images/pix.png" />
                    
                </div>
                
                <div id="bright">
                    <div>
                        <h2 class="header_small">Welcome</h2>
                        <h2 class="header_big">AIESEC Alumni HUB</h2>
                        
                        <div id="intro">The online space where over 1 Million AIESEC Alumni from all over the world get to connect, interact and creating long lasting Impact together.
                        <br/>
                        <br/>
                        
                        
                        
                       
                        
                        
                        
                        <a href="/linkedinlogin/" id='linkedinlogin'><img src="images/loginlinkedin.png" /></a>
                        
                        <br/><br/>
                        
                        
                        </div>
                        
                        
                        
                        
                        
                    </div>
                </div>
                
                
            