<?php


?>
<?php 
$appurl =  Zend_Registry::get('url');
?>
<img src='<?php echo $appurl?>/images/joingroup.jpg' alt='Thank you for your interest in AIESEC ALUMNIHUB.
It seems you are not a member of AIESEC Alumni Global Group
on linkedin. AIESEC Alumni Global is the official group of AIESEC
Alumni worldwide.

In other to use AIESEC ALUMNIHUB, you need to first join the group on Linkedin.
Once you are join you can return to login.' />

<div style='margin-left:70px'><a href='http://www.linkedin.com/groups?trk=myg_ugrp_ovr&gid=693' ><img src='<?php echo $appurl?>/images/joingrouplink.jpg' /></a>
<br/>
<p><a href='<?php echo $appurl?>' style='margin-left:20px'>Back to welcome page</a></p>
</div>