<!DOCTYPE html> 
<html lang="en"> 
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <head>
    <script type="text/javascript" src="/scripts/jquery.js">
    
    </script>
    
    <script type="text/javascript" src="/scripts/jqueryui.js">
    
    </script>
    
<script type='text/javascript' src='http://alumni.aiesec.org/scripts/bootstrap-modal.js'>

</script>
    
        <link rel="icon" type="image/jpg" href="/images/fave.png" />
        <link rel="stylesheet" href="/styles/bootstrap.min.css">
        <link rel="stylesheet" href="/styles/ui/base/jquery.ui.all.css">
        <link rel="stylesheet" href="/styles/master.css">
        <title>Welcome</title>
    </head>
    
    
    <body>
        
          <div class="container">
         
          <div class="content">
          <?php 
          echo $this->layout()->content;
          ?>
          </div>

            <div class="footer">
            <div><a href="http://alumni.aiesec.org">Welcome</a> | <a href="<?php echo Zend_Registry::get('url')?>/static/about">About AIESEC Alumni Hub</a> | <a  href="<?php echo Zend_Registry::get('url')?>/static/contact">Getting In Touch</a></div>
            </div>
          </div>
        
        
    </body>
    
</html>