<script type="text/javascript" src="<?php echo Zend_Registry::get('url'); ?>/scripts/projectform.js">

</script>
<script type='text/javascript' src='<?php echo Zend_Registry::get('url'); ?>/scripts/bootstrap-modal.js'>

</script>

<script type='text/javascript' src='<?php echo Zend_Registry::get('url'); ?>/scripts/vote.js'>

</script>

<style type='text/css'>
#my-modal h5
{
	text-align:center;
}

#my-modal p
{
	margin:0px 20px;
	text-align:justify;
}
</style>

<div id='my-modal' style=''>
<span style="display:block;background-color:#1a7fab;height:20px;">
</span>
<h5>Your Project Has Been Added</h5>
<br/>
<p>

Your Project would be active for a period of 8 weeks in which people can see your idea and get in touch with you as regards collaboration</p>
<a class='btn success' style='margin-left:316px;' href='<?php echo $this->userAgent()->getServerValue('request_uri'); ?>'>Close</a>
</div>
<div id="left_content">

<h2>StartUp HUB</h2>
<span id='intro'>
StartUp Hub allows you to find and collobborate with other AIESEC Alumnus over projects you are interested in.
<br/> To use the StartUp Hub, click the "Add your project" button below and proceed. Your Project would now be available to other 
Alumni and they can get in touch with you as regards colloborating on the project.
</span>



<!--<h3>Post Project</h3>-->

<div id="projectleft">
<div id='uploadform'>



<div id='infoproject'>
<span id='showclose'>Add Your Project <img style='width:13px;height:13px;vertical-align:middle;margin-top:-3px;margin-left:4px;'  src="<?php echo "/images/add.png" ?>" /></span>
</div>
<br/><br/>
<?php 
//library/helper/form/uploadproject.php
echo $this->uploadproject('addproject');
//library/helper/form/showprojects.php
echo "<h3>Recently Added Projects</h3>";

echo $this->showprojects('all');

?>
</div>
</div>

<div id="projectright">
<!--<h6>Most Voted Projects</h6>-->
<?php 
echo $this->projectcat();

?>

</div>



</div>

