<script type="text/javascript" src="<?php echo Zend_Registry::get('url');?>/scripts/projectform.js">

</script>
<script type='text/javascript' src='<?php echo Zend_Registry::get('url');?>/scripts/bootstrap-modal.js'>

</script>


<script type='text/javascript' src='<?php echo Zend_Registry::get('url');?>/scripts/vote.js'>

</script>

<div id='my-modal'>Hello World</div>
<div id="left_content">

<h2>StartUp HUB</h2>
<span id='intro'>
StartUp Hub allows you to find and collobborate with other AIESEC Alumnus over projects you are interested in
</span>



<!--<h3>Post Project</h3>-->

<div id="projectleft">
<div id='uploadform'>



<!-- <span id='showclose'> Add Your Project <img style='width:13px;height:13px;vertical-align:middle;margin-top:-3px;'  src="<?php echo "/images/add.png" ?>" /></span>-->

<?php 
//library/helper/form/showprojects.php
echo "<h3>Project</h3>";

if ($this->projectid) //if ProjectID is set
{
echo $this->showprojects('single',$this->projectid);
}
if ($this->category)
{
	echo $this->showprojects('single',$this->category);
}


?>
</div>
</div>

<div id="projectright">
<h6>Most Voted Projects</h6>
<?php 
echo $this->projectcat();
?>
</div>



</div>

