<div id="left_content">
<h3>Recent Newsletter</h3>

<span id="intro">
Have you read the latest Global AIESEC Alumni Newsletter? This is the join newsletter of AIESEC International and AIESEC Alumni International, where you can find latest updates on events, alumni initiatives and what is the alumni community engaged in worldwide.
</span>
<div style="padding-left:10px;">
<a href='http://www.aiesec-alumni.org/News_files/AAI-AI%20Newsletter%20January%202012.pdf' target='_blank'></a><img alt="" src="<?php Zend_Registry::get('url')?>/images/newsletter.png"></a>
</div>

<div>
<br/><br/>
You can find previously published newsletter from the <a href='http://www.aiesec-alumni.org/News.html' target='_blank'>AIESEC Alumni website</a>.
</div>

</div>