<style type='text/css'>
div#staticcontent
{
	margin:10px;
	padding:5px;
	
	width:890px;
}
</style>

<div id="staticcontent">
<h3>Welcome to AlumniHub</h3>
<p>AIESEC Alumni International (AAI) is a registered international, non-political, independent and non for profit association, linking its memberships above and beyond culture, race, sex, citizenship, religion, economic system and branch, hierarchy and generation, based on non-mercantile relationships and a capital of trust. Through its memberships, the association will continue to promote international and cross-cultural understanding, in line with the founding principles of AIESEC, for the professional and personal development of its members and the good of society.</p>

<p>AAI was founded 1986 when some active ex-AIESECers, exPAIs and exNCPs among them, started a new chapter in AIESEC history in Budapest, Hungary, shortly before the world started to change again - this time towards democracy and freedom.</p>

<p>AAI's mission is to provide an international platform through which former AIESEC members and associates can continue to interact, contribute to and actively gain from a continuing involvement with AIESEC and the Alumni of AIESEC. AAI actively promotes the ethics, values and culture of AIESEC within both the professional environments of its membership as well as other external environments.</p>

<p>We want to continue</p>
<ol>
<li>to develop socially responsible, culturally sensitive, proactive agents of change</li>
<li>to make a difference in society and the life of the individual</li>
<li>to fulfil the role that AIESEC plays within society through an Alumni body</li>
</ol>
</p>

<p>In 2008 the 60th anniversary events of AIESEC brought about through the initiative of AIESEC International proved to be a great success with celebrations ranging from London to Tokyo and from Brussels to Sao Paulo. Alumni owe a lot to AI for bringing this world-wide intergenerational group together.</p>

<p>It is now time for alumni to organize themselves and develop ways to contribute to the student movement which brought us all together in the first place. AIESEC sees the value of Alumni and Alumni want to maintain a link with the student body. This is why we should all respond "Present" to the invitation to participate at the Alumni get-together around the forthcoming Alumni Conferences.</p>

<p>Looking forward to hear from you and to meet many of you at the coming conferences!</p>

<p>
<strong>Brussels, 05.01.2009</strong><br/>
<strong>Victor H. Loewenstein</strong><br/>
<em>President 2009/10</em><br/>
<em>AIESEC Alumni International</em><br/>
</p>
</div>