<!DOCTYPE html> 
<html lang="en"> 
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <head>
    <script type="text/javascript" src="/scripts/jquery.js">
    
    </script>
    
    <script type="text/javascript" src="/scripts/jqueryui.js">
    
    </script>
    
<script type='text/javascript' src='http://alumni.aiesec.org/scripts/bootstrap-modal.js'>

</script>
    
        <link rel="icon" type="image/jpg" href="/images/fave.png" />
        <link rel="stylesheet" href="/styles/bootstrap.min.css">
        <link rel="stylesheet" href="/styles/ui/base/jquery.ui.all.css">
        <link rel="stylesheet" href="/styles/master.css">
        <title>Welcome</title>
        
        
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30439519-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>        
    </head>
    
    
    <body>
        
          <div class="container">
         
          <div class="content">
          <?php 
          echo $this->layout()->content;
          ?>
          </div>

            <div class="footer">
            <div><a href="http://alumni.aiesec.org">Welcome</a> | <a href="<?php echo Zend_Registry::get('url')?>/static/about">About AIESEC Alumni Hub</a> | <a  href="<?php echo Zend_Registry::get('url')?>/static/contact">Getting In Touch</a></div>
            </div>
          </div>
        
        
    </body>
    
</html>