<?php 
$appurl = Zend_Registry::get('url');

          @session_start();
          if(!isset($_SESSION['aid']))
          {
          	echo "Setting First time";
          $l = new Linkedin_login();
          

          if($l->isGroupmember('693'))
          {
          $l->displaylinkedinprofile();
          $_SESSION['profilepix'] = (string)$l->profilepix;
          $_SESSION['firstname'] = (string)$l->firstname;
          $_SESSION['lastname'] = (string)$l->lastname;
          $_SESSION['industry'] = (string)$l->industry;
          $_SESSION['headline'] = (string)$l->headline;
          $_SESSION['aid'] = (string)$l->aid;
          $_SESSION['publiclink'] = (string)$l->publiclink;		
          }
          else 
          {
          	//direct to page where they login
          	$appurl = Zend_Registry::get('url');
          	header("location:$appurl/index/join");
          }
          
          
          
          
          
          
          
          }
            
         
          
          
          ?>
          


<!DOCTYPE html> 
<html lang="en"> 
    <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
     <script type="text/javascript" src="/scripts/jquery.js">
    
    </script>
    
    <script type="text/javascript" src="/scripts/jqueryui.js">
    
    </script>
        
        <link rel="stylesheet" href="/styles/bootstrap.min.css">
        <link rel="stylesheet" href="/styles/ui/base/jquery.ui.all.css">
        <link rel="icon" type="image/jpg" href="/images/fave.png" />
        <link rel="stylesheet" href="/styles/master.css">
        <link rel="stylesheet" href="/styles/home.css">
        <?php echo $this->headTitle();?>
    </head>
    
    
    
    <body>
        <div class="nav">
        <img style="display:inline;position:fixed;left:30px;top:7px" src="<?php echo $appurl;?>/images/beta.png" />
        <ul>
        <li><a href="<?php echo $this->baseUrl('home'); ?>">Home</a></li>
        <li><a href="<?php echo $this->baseUrl('a2a/directory'); ?>">Alumni Offices Worldwide</a></li>
        <li><a href="<?php echo $this->baseUrl('a2a/findalumni'); ?>">Find Alumni</a></li>
        <li><a href="<?php echo $this->baseUrl('a2a/startuphub'); ?>">StartUp Hub</a></li>
        <li><a href="<?php echo $this->baseUrl('a2w/blog'); ?>">Alumni Blog</a></li>
        <li style='margin-right:90px;'><a href="<?php echo $this->baseUrl('settings/logout'); ?>">Log Out</a></li>
        <!-- <li id='profile'><a href='<?php echo $this->baseUrl('settings/profile'); ?>'>Go to your profile<img src='<?php echo  $_SESSION['profilepix'] ?>'/></a></li>-->
        </ul>
        <div style="margin-top:-5px;margin-right:-700px;color:#fff"> Share on linkedin <script src="http://platform.linkedin.com/in.js" type="text/javascript"></script><script type="IN/Share" data-url="alumni.aiesec.org" data-counter="right"></script></div>
        
        <!-- <ul>
        <li><a href="<?php echo $this->baseUrl('home'); ?>">Home</a></li>
        <li><a href="<?php echo $this->baseUrl('home'); ?>">Alumni2Alumni</a></li>
        <li><a href="<?php echo $this->baseUrl('home'); ?>">Alumni2AIESEC</a></li>
        <li><a href="<?php echo $this->baseUrl('home'); ?>">Alumni2World</a></li>
        <li><a href="<?php echo $this->baseUrl('settings/logout'); ?>">Log Out</a></li>
        </ul>-->
        
        </div>
        
        
        
        <div style="clear:both"></div>
        <br/><br/><br/><br/>
          <div class="container">
          <div class="content">
           <div id="left">
          <?php 
          echo $this->layout()->content;
          ?>
          </div>
          <div id="profile_sidebar">
          
          
          
          <div style="width:180px;">
		    <img class= "profile_pix" src="<?php echo $_SESSION['profilepix']?>" />
		    <br/>
		    <p class="profile_p"><span class='profile_label'>First Name</span> <br/> <?php echo $_SESSION['firstname'] ?></p>
		    <p class="profile_p"><span class='profile_label'>Last Name</span> <br/> <?php echo $_SESSION['lastname'] ?></p>
		    <p class="profile_p"><span class='profile_label'>Industry</span> <br/><?php echo $_SESSION['industry'] ?></p>
		    <p class="profile_p"><span class='profile_label'>Position</span> <br/><?php echo $_SESSION['headline'] ?></p>
		    <p style="display:none;" id='profileid' class="profile_p"><?php echo $_SESSION['aid'] ?></p>
		    <br/>
		    <?php 
		    $uri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
		    if($this->placeholder('addaiesec') && $uri != "/settings")
		    {
		    
		    //if the use has not added any AIESEC info
		    $db = new Settings_Model_Profiledb();
		    if (count($db->getMember($_SESSION['aid'])) == 0)
		    echo "<a style='margin-left:5px;font-size:10px;' class='btn primary' href='/settings'>Add AIESEC Information</a>";
		    else 
		    echo "<a style='margin-left:5px' class='btn primary' href='/settings/profile'>View Your Profile</a>";
		    //put the Update AIESEC button
		    
		    
		    }
		     
		    
		    
		    
		 
		    ?>
	
		    
</div>
<h5>Other Alumni</h5>
<div class='hubmembers'>

<?php 
$this->hubmembers();
?>
</div>
          </div>
          
          
          </div>

            
            <div class="footer">
            <div><a href="<?php echo Zend_Registry::get('url')?>/static/about">About AIESEC Alumni Hub</a>  <a  href="<?php echo Zend_Registry::get('url')?>/static/contact">Getting In Touch</a></div>
            </div>
            
          </div>
        
<div><!-- so javascript can easily pick the appurl -->
<?php 
$appurl = Zend_Registry::get('url');
?>
<input type='hidden' id='appurl' value='<?php echo $appurl?>' />
</div>
    </body>
    
</html>