<div id="left_content">


<span id='intro'>
Here is a list of the various awards that are awarded to AIESEC Alumni.
</span>

<div id='inner_content'>

<h5>Global AIESEC Contribution Award</h5>

<p>This award is presented to those individuals who make and outstanding contribution to AIESEC in their countries by participating in a wide range of activities, including national conferences, partnerships, alumni organizations and serving on advisory boards of AIESEC entities.</p>

<p>The aim of this award is to increase the involvement of alumni and encourage those who continue to make a difference for AIESEC.</p>

<h5>Global AIESEC Alumni Entrepreneurship and Leadership Award</h5>

<p>This award is presented to an alumnus who has made a considerable achievement as an entrepreneur and leader in his / her field of engagement.</p> 

<p>The aim of this award is to showcase the achievements of alumni who have been involved in developing ideas into successful entrepreneurial or social setups or achieved significant personal results in the community and while doing so, continuing to support AIESEC and demonstrating leadership in their areas of business and society.</p>

<h5>Global AIESEC Alumni Hall of Fame Award</h5>

<p>This award is presented to alumni who had an outstanding contribution while being in AIESEC and after leaving the organization and who had demonstrated active leadership throughout their lives. They were or are still involved in local national or international activities, offering advice and support to the AIESEC membership.</p>

<p>The aim of this award is to show to the world the impact that AIESEC alumni have in society and to acknowledge their contribution. We would like to reinforce the leadership characteristics, excellence and attitudes desired in our organization by highlighting alumni who exemplify our values.</p>


<h5>Global Young AIESEC Alumni Contribution Award</h5>

<p>This award is presented to those young alumni who make an outstanding contribution to AIESEC by participating in a wide range of activities, including and not limited to national conferences, partnerships, Alumni Clubs and Associations and serving on Boards of Member/National Committees.</p> 

<p>The aim of this award is to increase the involvement of alumni and especially young alumni and to recognize and encourage those who make a difference for AIESEC even in their early careers.</p>


</div>
</div>

